### ISSUE TITLE
🚧   Fix the picture in ~/succes

### ISSUE THREAD

**Issue by ParvinBDJ** [dewarian/Dating-Shreks#30]
#Fix the picture in ~/succes

## Description
The pictures in the succes page are looking funny. I would want them differently but I cant seem to figure out where to change this. @uxtothemax do you want to help me?

**Comment by uxtothemax** [comment]
Yeah I saw that too! I'll fix it tonight, no problem! It was difficult to write CSS on a static file, so I need to rewrite some lines. I will comment on this thread how i fixed it :)

**Comment by uxtothemax** [comment]
Fixed!

I also made the css for images more generic 😄 

Old code for succes images:
![old-li-img](https://user-images.githubusercontent.com/64483507/85337023-fb987200-b4df-11ea-8429-1fcf2cf9b18e.PNG)

New code for all images (including succes):
![new-li-img](https://user-images.githubusercontent.com/64483507/85337034-ff2bf900-b4df-11ea-9eda-ab06a7116598.PNG)

This is not the entire code for the images. I wrote more specific css for the radio images. It was tricky to keep it responsive, because html of the radio img and succes img are different of course.
